#include QMK_KEYBOARD_H
#if __has_include("keymap.h")
#    include "keymap.h"
#endif
#include "raw_hid.h"

// Define some keycodes
#define LL_NUMSYM OSL(_NUMSYM) // Left tuck thumbkey oneshot mod numsym layer
#define RL_NUMSYM OSL(_NUMSYM) // Right tuck thumbkey oneshot mod numsym layer
/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */

enum custom_keycodes {
  TMUX_PASTE = SAFE_RANGE,
  TMUX_MENU,
  TMUX_CMODE,
  TMUX_PANE_L,
  TMUX_PANE_D,
  TMUX_PANE_U,
  TMUX_PANE_R,
  TMUX_HSPLIT,
  TMUX_VSPLIT,
};

enum layers {
  _DVORAK,
  _NAV,
  _NUMSYM,
  _FUNC,
  _MOUSE
};



const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
// Dvorak
    [_DVORAK] = LAYOUT_split_3x5_3(
		    KC_QUOT,         KC_COMM,        KC_DOT,         KC_P,     KC_Y,    			KC_F,      KC_G,         KC_C,         KC_R,         KC_L,
		    KC_A,            KC_O,           KC_E,           KC_U,     KC_I,				KC_D,      KC_H,         KC_T,         KC_N,         KC_S,
		    LALT_T(KC_SCLN), LGUI_T(KC_Q), LSFT_T(KC_J), LCTL_T(KC_K), KC_X, 				KC_B,      RCTL_T(KC_M), RSFT_T(KC_W), RGUI_T(KC_V), RALT_T(KC_Z),
		                                    OS_LSFT,  KC_BSPC,  LT(_NAV,KC_ESC),		KC_ENT,  KC_SPC,  RL_NUMSYM
    ),
// Navigation
    [_NAV] = LAYOUT_split_3x5_3(
		    LCA(KC_DEL),     KC_TRNS,       LCS(KC_TAB), LCTL(KC_TAB), KC_DEL,				KC_PSCR,   KC_HOME,      KC_PGDN,      KC_PGUP,      KC_END,
		    KC_TRNS,         KC_LALT,       LSFT(KC_TAB),     KC_TAB,  KC_CAPS,				TMUX_VSPLIT,   KC_LEFT,      KC_DOWN,      KC_UP,        KC_RGHT,
		    KC_TRNS,         KC_TRNS,       KC_TRNS,   LCTL_T(KC_INS), CW_TOGG,				TMUX_HSPLIT,   TMUX_PANE_L,  TMUX_PANE_D,  TMUX_PANE_U,  TMUX_PANE_R,
		    		                    KC_TRNS,     KC_TRNS,      KC_TRNS,				KC_TRNS,   KC_TRNS,      KC_TRNS
    ),
// NumSym
    [_NUMSYM] = LAYOUT_split_3x5_3(
		    TMUX_MENU,         TMUX_PASTE,       KC_LBRC,      KC_RBRC,     KC_TRNS,				KC_BSLS,   KC_7,         KC_8,         KC_9,         KC_EQL,
		    TMUX_MENU,         TMUX_CMODE,       KC_LPRN,      KC_RPRN,     KC_TRNS,				KC_SLSH,   KC_4,         KC_5,         KC_6,         KC_MINS,
		    KC_TRNS,   LGUI_T(KC_GRV), LSFT_T(KC_BSLS), LCTL_T(KC_SLSH), KC_TRNS,			KC_0,      RCTL_T(KC_1), RSFT_T(KC_2), RGUI_T(KC_3), RALT_T(KC_DOT),
		                                    KC_TRNS,     KC_TRNS,      KC_TRNS,				KC_TRNS,   KC_TRNS,      KC_TRNS
		    ),
// Function
    [_FUNC] = LAYOUT_split_3x5_3(
		    KC_TRNS,         KC_F7,         KC_F8,            KC_F9,   KC_F12, 				KC_BRIU,   KC_MRWD,      KC_MPLY,      KC_MFFD,      KC_TRNS,   
		    KC_TRNS,         KC_F4,         KC_F5,            KC_F6,   KC_F11,				KC_BRID,   KC_MUTE,      KC_VOLD,      KC_VOLU,      KC_TRNS,
		    KC_TRNS,         KC_F1,         KC_F2,            KC_F3,   KC_F10,				KC_TRNS,   KC_TRNS,      KC_TRNS,      KC_TRNS,      KC_TRNS,
		    		                    KC_TRNS,     KC_TRNS,      KC_TRNS,				KC_TRNS,   KC_TRNS,      KC_TRNS
		    ),
// Mouse
    [_MOUSE] = LAYOUT_split_3x5_3(
		    QK_BOOT,         KC_TRNS,       KC_TRNS,          KC_TRNS, KC_DEL,				KC_TRNS,   MS_WHLL,      MS_WHLD,      MS_WHLU,      MS_WHLR,
		    QK_RBT,         KC_TRNS,       KC_TRNS,          KC_TRNS,  KC_TRNS,			KC_TRNS,   MS_LEFT,      MS_DOWN,      MS_UP,        MS_RGHT,
		    KC_TRNS,         KC_TRNS,       KC_TRNS,          KC_TRNS, KC_TRNS,				KC_TRNS,   KC_TRNS,      KC_TRNS,      KC_TRNS,      KC_TRNS,
		    		                    KC_TRNS,     KC_TRNS,      KC_TRNS,				MS_BTN1,   MS_BTN2,      KC_TRNS
    )
};

const char chordal_hold_layout[MATRIX_ROWS][MATRIX_COLS] PROGMEM = LAYOUT_split_3x5_3(
  'L', 'L', 'L', 'L', 'L',
  'L', 'L', 'L', 'L', 'L',
  'L', 'L', 'L', 'L', 'L',
  '*', '*', '*',
  'R', 'R', 'R', 'R', 'R',
  'R', 'R', 'R', 'R', 'R',
  'R', 'R', 'R', 'R', 'R',
  '*', '*', '*'
);

// combo definitions
const uint16_t PROGMEM combo0[] = { KC_BSPC, KC_SPACE, COMBO_END};
const uint16_t PROGMEM combo1[] = { KC_BSPC, KC_ENT, COMBO_END};
//const uint16_t PROGMEM combo2[] = { KC_E, KC_BSPC, COMBO_END};
//const uint16_t PROGMEM combo3[] = { KC_SPC, KC_T, COMBO_END};

// combo outputs
combo_t key_combos[COMBO_COUNT] = {
    COMBO(combo0, OSL(_FUNC)),
    COMBO(combo1, OSL(_MOUSE)),
    //COMBO(combo2, OS_LSFT),
    //COMBO(combo3, OS_RSFT),
};

// per-key tapping term definitions
uint16_t get_tapping_term(uint16_t keycode, keyrecord_t *record) {
    switch (keycode) {
        case LT(_NAV, KC_ESC):
            return 150;
        default:
            return TAPPING_TERM;
    }
}

// Macro definitions function
bool process_record_user(uint16_t keycode, keyrecord_t *record) {
  switch (keycode) {
    case TMUX_PASTE:
    if (record->event.pressed) {
      SEND_STRING(SS_LCTL(SS_TAP(X_B))SS_DELAY(100)  SS_TAP(X_RBRC));
    }
    break;
    case TMUX_MENU:
    if (record->event.pressed) {
      SEND_STRING(SS_LCTL(SS_TAP(X_B))SS_DELAY(100)  SS_TAP(X_EQL));
    }
    break;
    case TMUX_CMODE:
    if (record->event.pressed) {
      SEND_STRING(SS_LCTL(SS_TAP(X_B))SS_DELAY(100)  SS_TAP(X_LBRC));
    }
    break;
    case TMUX_PANE_L:
    if (record->event.pressed) {
      SEND_STRING(SS_LCTL(SS_TAP(X_B))SS_DELAY(100)  SS_TAP(X_H));
    }
    break;
    case TMUX_PANE_D:
    if (record->event.pressed) {
      SEND_STRING(SS_LCTL(SS_TAP(X_B))SS_DELAY(100)  SS_TAP(X_T));
    }
    break;
    case TMUX_PANE_U:
    if (record->event.pressed) {
      SEND_STRING(SS_LCTL(SS_TAP(X_B))SS_DELAY(100)  SS_TAP(X_N));
    }
    break;
    case TMUX_PANE_R:
    if (record->event.pressed) {
      SEND_STRING(SS_LCTL(SS_TAP(X_B))SS_DELAY(100)  SS_TAP(X_S));
    }
    break;
    case TMUX_HSPLIT:
    if (record->event.pressed) {
      SEND_STRING(SS_LCTL(SS_TAP(X_B))SS_DELAY(100)  SS_RSFT(SS_TAP(X_QUOT)));
    }
    break;
    case TMUX_VSPLIT:
    if (record->event.pressed) {
      SEND_STRING(SS_LCTL(SS_TAP(X_B))SS_DELAY(100)  SS_RSFT(SS_TAP(X_5)));
    }
    break;

  }
  return true;


}

// keymap layer companion function
layer_state_t layer_state_set_user(layer_state_t state) {
    uint8_t hi_layer = get_highest_layer(state);
    uint8_t response[RAW_EPSIZE];
    memset(response, 0x00, RAW_EPSIZE);
    response[PAYLOAD_BEGIN] = PAYLOAD_MARK;
    response[PAYLOAD_BEGIN + 1] = hi_layer;
    raw_hid_send(response, RAW_EPSIZE);
    return state;
}


#ifdef OTHER_KEYMAP_C
#    include OTHER_KEYMAP_C
#endif // OTHER_KEYMAP_C


